# Generated by Django 3.1.12 on 2025-03-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='json_data_collection',
        ),
    ]
