# Generated by Django 3.1.12 on 2025-03-20 21:16

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0002_auto_20250320_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
