# Generated by Django 3.1.12 on 2025-03-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0003_auto_20250320_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
