# Generated by Django 3.1.12 on 2025-03-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0005_auto_20250320_2118'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
    ]
