# Generated by Django 3.1.12 on 2025-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0008_auto_20250320_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
